- name: Install required packages
  ansible.builtin.package:
    name: "{{ users_requirements }}"
    state: present

- name: Create sudoers directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure sudoers directory
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    regexp: "^[#@]includedir .*"
    owner: root
    group: root
    mode: 0440
    validate: visudo -cf %s

- name: Setup groups
  when: >
    users_groups is defined and
    users_groups is iterable and
    users_groups is not none
  ansible.builtin.include_tasks: group.yml
  loop: "{{ users_groups }}"
  loop_control:
    label: "{{ item.name }}"

- name: Setup users
  when: >
    users is defined and
    users is iterable and
    users is not none
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
